baseURL = "https://youtangai.github.io/"
languageCode = "en-us"
title = "youtangai's blog"
theme = "diary"
copyright = "Copyright © 2019–2021, youtangai; all rights reserved."
googleAnalytics = "UA-154413959-1"

[params]
subtitle = "Themed by Diary."
enableGitalk = false

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "youtangaiのブログ" # will set 'og:site_name'
description = "youtangaiのブログです"  # will set 'og:description'

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2
[[menu.main]]
  name = "Blog"
  url = "/posts"
  weight = 3