baseURL = "https://youtangai.github.io/"
languageCode = "en-us"
title = "youtangai's blog"
theme = "diary"
copyright = "Copyright © 2019–2021, youtangai; all rights reserved."
googleAnalytics = "UA-154413959-1"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "Themed by Diary."
enableGitalk = false

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "youtangaiのブログ" # will set 'og:site_name'
description = "youtangaiのブログです"  # will set 'og:description'

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2
[[menu.main]]
  name = "Blog"
  url = "/posts"
  weight = 3
[[menu.main]]
  name = "Categories"
  url = "/categories"
  weight = 4
[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 5